version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies
      - mvn install -DskipTests
  build:
    commands:
      - echo Building the Spring Boot application
      - mvn clean package
  post_build:
    commands:
      - echo Preparing deployment zip
      - mkdir -p deploy
      - cp target/*.jar deploy/
      - cd deploy
      - zip -r ../aws-basic-app.zip .
      - cd ..

artifacts:
  files:
    - aws-basic-app.zip
